version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=hakaton_db
      - POSTGRES_USER=pavel
      - POSTGRES_PASSWORD=paveladmin
    ports:
      - "5433:5432"