services:
  - type: web
    name: scientific-community-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d4ma55shg0os73bnboug-a.oregon-postgres.render.com:5432/scientific_community?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: scientific_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: ldSPZkePR9VJukvrny3CnmMMRobsfAx2
      - key: GEMINI_API_KEY
        value: AIzaSyBOwcUr3ZFiPkVYhmc3TWSorn2k_vPU__c
      - key: CLOUDINARY_URL
        value: cloudinary://724566716965946:K02_WJMhAC0usIcMUOXTz0JdO-k@dgwu07lgw
    plan: free